Desktop/repo/DutchTreat/DutchTreat/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DutchTreat.Data;
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DutchTreat.Controllers
{
  public class AppController : Controller
  {
    private readonly IMailService _mailService;
    private readonly IDutchRepository _repository;

    public AppController(IMailService mailService, IDutchRepository repository)
    {
      _mailService = mailService;
      _repository = repository;
    }

    public IActionResult Index()
    {
      return View();
    }

    [HttpGet("contact")]
    public IActionResult Contact()
    {
      return View();
    }

    [HttpPost("contact")]
    public IActionResult Contact(ContactViewModel model)
    {
      if (ModelState.IsValid)
      {
        // Send the email
        _mailService.SendMessage("shawn@wildermuth.com", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
        ViewBag.UserMessage = "Mail Sent";
        ModelState.Clear();
      }

      return View();
    }

    public IActionResult About()
    {
      ViewBag.Title = "About Us";

      return View();
    }

    public IActionResult Shop()
    {
      return View();
    }

  }
}

Desktop/repo/DutchTreat/DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <title>Dutch Treat: @ViewBag.Title</title>
  <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
  <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
  <header class="container">
    <nav class="navbar navbar-dark bg-dark navbar-expand-md">
      <h1 class="navbar-brand"><i class="fa fa-paint-brush"></i> Welcome to Dutch Treat</h1>
      <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="theMenu" class="navbar-collapse collapse">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" asp-controller="App" asp-action="Index">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="App" asp-action="About">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-controller="App" asp-action="Shop">Shop</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <section class="container">
    <h2 class="text-center">@ViewBag.Title</h2>
    @RenderBody()
  </section>
  <footer class="container">
    <div class="text-center">Copyright 2017 Dutch Treat LLC</div>
  </footer>


  <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
  <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/index.js"></script>
  @RenderSection("scripts", false)
</body>
</html>